name: Release Latest

on: [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: DOCKER_BUILDKIT=1 docker build --progress=plain --platform linux/amd64,linux/arm64 -t ghcr.io/${GITHUB_REPOSITORY}/${GITHUB_REF##*/} .

      - name: Tag image
        run: docker tag ghcr.io/${GITHUB_REPOSITORY}/${GITHUB_REF##*/} ghcr.io/rob-luke/emails-html-to-pdf:latest

      - name: Push image to github
        run: docker push ghcr.io/rob-luke/emails-html-to-pdf:latest
